# ------------------- basic -------------------- #
seed: 1024
input_dims: 2
output_dims: 2
# ------------------- data ------------------- #
# state of initial data
state_num: 2
# box length(calculate area)
box_l: 2
# calculate time
time_total: 2
# time step
delta_time: 0.00001
# space step
delta_x: 0.01

# number of boundary data sampling
boundary_num: 50
# number of initial data sampling
initial_num: 50
# number of common data sampling
common_num: 20000

# data loader batch size
# "-1" means loader all data
boundary_batch_size: -1
initial_batch_size: -1
common_batch_size: -1

# ------------------- model ------------------- #
model_layers: [100, 100, 100, 100]

# ------------------- train ------------------- #
max_epochs: 2000

lr: 1.0
max_iter: 50000
max_eval: 50000
history_size: 50
tolerance_grad: 1e-5
line_search_fn: "strong_wolfe"

# ------------------- save ------------------- #
figure_output_root: "./output/plots"
model_output_root: "./output/weights"

numerical_figure_output_name: "shrodinger_equation_FD_fourth_Lounge_Kutta.png"
pinn_figure_output_name: ""
model_output_name: "shrodinger_equation_pinn.pth"
