# ------------------- basic -------------------- #
func_name: "1d_heat_transfer_equation"
seed: 1024
input_dims: 2
output_dims: 1
# ------------------- data ------------------- #
# box length(calculate area)
cal_x_range: [0, 1]
# calculate time
time_total: 20
# time step
delta_time: 0.0001
# space step
delta_x: 0.01

# number of boundary data sampling
boundary_num: 70
# number of initial data sampling
initial_num: 30
# number of common data sampling
common_num: 20000

# data loader batch size
# "-1" means loader all data
boundary_batch_size: -1
initial_batch_size: -1
common_batch_size: -1

# ------------------- model ------------------- #
model_layers: [20, 20, 20, 20, 20, 20, 20, 20, 20]
load_weight: "False"

# ------------------- train ------------------- #
train_model: "True"
max_epochs: 5000

# optimizer
lr: 0.2
max_iter: 50000
max_eval: 50000
history_size: 50
tolerance_grad: 1e-5
line_search_fn: "strong_wolfe"

# ------------------- save ------------------- #
numerical_plot: "True"
PINN_plot: "True"

figure_output_root: "./output/plots"
model_output_root: "./output/weights"

numerical_figure_output_name: "1d_heat_transfer_equation_numerical.png"
numerical_gif_output_name: "1d_heat_transfer_equation_numerical.gif"
pinn_figure_output_name: "1d_heat_transfer_equation_PINN.png"
pinn_gif_output_name: "1d_heat_transfer_equation_PINN.gif"
model_output_name: "1d_heat_transfer_equation_pinn.pth"

different_figure_output_name: "1d_heat_transfer_equation_different.png"
different_gif_output_name: "1d_heat_transfer_equation_different.gif"
